[workspace]
resolver = "2"
members = [
	"crawler",
	"entrypoint"
]

[workspace.dependencies]
crawler = { path = "./crawler" }
retailers = { path = "./retailers" }
reqwest = "0.12.15"
serde_json = "1.0.140"
serde = "1.0.219"
tokio = "1.44.2"
scraper = "0.23.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
async-trait = "0.1.88"