[workspace]
resolver = "2"
members = [
	"crawler",
	"entrypoint",
	"retailers",
	"mongodb_connector"
]

[workspace.dependencies]
crawler = { path = "./crawler" }
retailers = { path = "./retailers" }
mongodb_connector = { path = "./mongodb_connector" }
reqwest = "0.12.15"
serde_json = "1.0.140"
serde = "1.0.219"
tokio = "1.44.2"
scraper = "0.23.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
async-trait = "0.1.88"
mongodb = "3.2.3"
axum = "0.8.4"
tower-http = "0.6.4"
tower = "0.5.2"
regex = "1.11.1"
thiserror = "2.0.12"
